### ISSUE TITLE
can not install heroku-container-registry

### ISSUE THREAD

**Issue by nhat-dinh** [heroku/heroku-container-registry#22]
My circle-ci deployment failed with the following error, please check this.

```
set git remote heroku to https://git.heroku.com/repo-name.git
 ▸    heroku-cli: update available from 6.12.9 to 6.13.19-6cd27b3
Installing plugin heroku-container-registry... !
 ▸    yarn --non-interactive --mutex=file:/home/ubuntu/.cache/heroku/yarn
 ▸    --cache-folder=/home/ubuntu/.cache/heroku/yarn exited with code 1
 ▸    error An unexpected error occurred:
 ▸    "http://cli-npm.heroku.com/mimic-fn/-/mimic-fn-1.1.0/e667783d92e89dbd342818b5230b9d62a672ad18/e667783d92e89dbd342818b5230b9d62a672ad18.tgz:
 ▸    Request failed \"500 Internal Server Error\"".
 ▸    

     ▸    heroku-cli: update available from 6.12.9 to 6.13.19-6cd27b3
     ▸    container:push is not a heroku command.
     ▸    Perhaps you meant commands
     ▸    Run heroku help for a list of available commands.
```

**Comment by ipranay** [comment]
+1 We're facing a similar issue.

```
Installing plugin heroku-container-registry... !
 ▸    yarn --non-interactive --mutex=file:/root/.cache/heroku/yarn
 ▸    --cache-folder=/root/.cache/heroku/yarn exited with code 1
 ▸    error An unexpected error occurred:
 ▸    "http://cli-npm.heroku.com/is-promise/-/is-promise-2.1.0/79a2a9ece7f096e80f36d2b2f3bc16c1ff4bf3fa/79a2a9ece7f096e80f36d2b2f3bc16c1ff4bf3fa.tgz:
 ▸    Request failed \"500 Internal Server Error\"".
```

**Comment by hanula** [comment]
Same issue, even after upgrading `heroku-cli` (via `apt-get install heroku`)

```
ubuntu@box1267:~$ export HEROKU_DEBUG=1                                                                                                                                                       
ubuntu@box1267:~$ heroku plugins:install heroku-container-registry                                                                                                                            
yarn install v0.27.5                                                                                                                                                                          
[1/4] Resolving packages...                                                                                                                                                                   
[2/4] Fetching packages...                                                                                                                                                                    
error An unexpected error occurred: "http://cli-npm.heroku.com/mimic-fn/-/mimic-fn-1.1.0/e667783d92e89dbd342818b5230b9d62a672ad18/e667783d92e89dbd342818b5230b9d62a672ad18.tgz: Request failed \"500 Internal Server Error\"".                                                                                                                                                               
info If you think this is a bug, please open a bug report with the information provided in "/home/ubuntu/.local/share/heroku/plugins/yarn-error.log".                                         
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.                                                                                                      
Error: yarn --non-interactive --mutex=file:/home/ubuntu/.cache/heroku/yarn --cache-folder=/home/ubuntu/.cache/heroku/yarn exited with code 1                                                  
error An unexpected error occurred: "http://cli-npm.heroku.com/mimic-fn/-/mimic-fn-1.1.0/e667783d92e89dbd342818b5230b9d62a672ad18/e667783d92e89dbd342818b5230b9d62a672ad18.tgz: Request failed \"500 Internal Server Error\"".                                                                                                                                                               
                                                                                                                                                                                              
    at ChildProcess.forked.on.code (/usr/lib/heroku/node_modules/cli-engine/lib/plugins/yarn.js:90:18)                                                                                        
    at emitTwo (events.js:125:13)                                                                                                                                                             
    at ChildProcess.emit (events.js:213:7)                                                                                                                                                    
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)                                                                                                                 
Exiting with code: 1   
```

```
ubuntu@box1267:~$ heroku version                                                                                                                                                              
heroku-cli/6.13.19 (linux-x64) node-v8.3.0
```

```
ubuntu@box1267:~$ uname -a                                                                                                                                                                    
Linux box1267.localdomain 3.13.0-125-generic #174-Ubuntu SMP Mon Jul 10 18:51:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by golubitsky** [comment]
Same problem with Travis.
```
$ export HEROKU_DEBUG=1  
$ heroku plugins:install heroku-container-registry
yarn install v0.24.6
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "http://cli-npm.heroku.com/mimic-fn/-/mimic-fn-1.1.0/e667783d92e89dbd342818b5230b9d62a672ad18/e667783d92e89dbd342818b5230b9d62a672ad18.tgz: Request failed \"500 Internal Server Error\"".
info If you think this is a bug, please open a bug report with the information provided in "/home/travis/.local/share/heroku/plugins/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: yarn --non-interactive --mutex=file:/home/travis/.cache/heroku/yarn --cache-folder=/home/travis/.cache/heroku/yarn exited with code 1
error An unexpected error occurred: "http://cli-npm.heroku.com/mimic-fn/-/mimic-fn-1.1.0/e667783d92e89dbd342818b5230b9d62a672ad18/e667783d92e89dbd342818b5230b9d62a672ad18.tgz: Request failed \"500 Internal Server Error\"".
    at ChildProcess.forked.on.code (/usr/local/heroku/node_modules/cli-engine/lib/plugins/yarn.js:90:18)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
Exiting with code: 1
```
```
$ heroku version 
heroku-cli/6.12.5-17216bc (linux-x64) node-v8.1.3
```

**Comment by nhat-dinh** [comment]
Problem solved by fixing  **circle.yml** file.

```diff
+ wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
- heroku plugins:install heroku-container-registry
```

**Comment by ipranay** [comment]
Looks like this was an issue with the npm package manager on heroku side. And has since been fixed.

**Comment by dmathieu** [comment]
ping @jdxcode

**Comment by jdx** [comment]
yes, this is fixed now, sorry for the trouble
