### ISSUE TITLE
#27 appears to have broken the CLI component

### ISSUE THREAD

**Issue by ircmaxell** [heroku/heroku-container-registry#33]
PR #27 added support for pass-by-stdin for Docker. This is fine by itself, but it also included references to an undefined variable `options`. This unfortunately breaks the plugin and is preventing login/deployment/etc via the heroku container registry.

## Steps to reproduce:

1. Run `heroku container:login`

## Expected:

Successful login

## Actual:

 ▸    Error: docker login exited with ReferenceError: options is not defined

## Backtrace

```
ReferenceError: options is not defined
    at Function.Sanbashi.cmd (/home/blah/.local/share/heroku/plugins/node_modules/heroku-container-registry/lib/sanbashi.js:126:3)
    at dockerLogin (/home/blah/.local/share/heroku/plugins/node_modules/heroku-container-registry/commands/login.js:43:19)
    at login (/home/blah/.local/share/heroku/plugins/node_modules/heroku-container-registry/commands/login.js:25:22)
    at run (/home/blah/.local/share/heroku/plugins/node_modules/heroku-cli-util/lib/command.js:159:15)
    at Object.run (/home/blah/.local/share/heroku/plugins/node_modules/heroku-cli-util/lib/command.js:171:12)
    at V5.run (/usr/lib/heroku/lib/legacy.js:58:16)
    at Function.run (/usr/lib/heroku/node_modules/cli-engine-command/lib/command.js:52:17)
    at <anonymous>
```

**Comment by dmathieu** [comment]
Thank you for the awesome detailed report.
heroku/heroku-container-registry/pull/32 is fixing this, and I've releases 4.4.3 a few minutes ago.
