### ISSUE TITLE
ESOCKETTIMEDOUT on running `heroku plugins:install heroku-container-registry`

### ISSUE THREAD

**Issue by khurramHazen** [heroku/heroku-container-registry#57]
I am running `heroku plugins:install heroku-container-registry` on local machine and getting this error. I am copy/pasting the contents of "yarn-error.log" here

```
Arguments: 
  /usr/lib/heroku/bin/node /usr/lib/heroku/node_modules/yarn/bin/yarn.js add heroku-container-registry@latest --non-interactive --mutex=file:/home/khurram/.local/share/heroku/plugins/yarn.lock --preferred-cache-folder=/home/khurram/.cache/heroku/yarn --registry=https://cli-npm.heroku.com

PATH: 
  /usr/lib/heroku/bin:/home/khurram/miniconda3/bin:/usr/local/cuda-9.0/bin:/home/khurram/bin:/home/khurram/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

Yarn version: 
  1.6.0

Node version: 
  9.11.1

Platform: 
  linux x64

Trace: 
  Error: http://cli-npm.heroku.com/rx/-/rx-4.1.0/a5f13ff79ef3b740fe30aa803fb09f98805d4782.tgz: ESOCKETTIMEDOUT
      at ClientRequest.<anonymous> (/usr/lib/heroku/node_modules/yarn/lib/cli.js:133786:19)
      at Object.onceWrapper (events.js:272:13)
      at ClientRequest.emit (events.js:180:13)
      at Socket.emitTimeout (_http_client.js:703:34)
      at Object.onceWrapper (events.js:272:13)
      at Socket.emit (events.js:180:13)
      at Socket._onTimeout (net.js:396:8)
      at ontimeout (timers.js:466:11)
      at tryOnTimeout (timers.js:304:5)
      at Timer.listOnTimeout (timers.js:267:5)

npm manifest: 
  {
    "private": true,
    "cli-engine": {
      "schema": 1
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

```

**Comment by dmathieu** [comment]
cc @heroku/cli

**Comment by jdx** [comment]
this plugin is included into the CLI by default, there is no need to install it. That's not the right name of the plugin either.
