### ISSUE TITLE
Error: Cannot find module 'inflection'

### ISSUE THREAD

**Issue by vazexqi** [heroku/heroku-container-registry#8]
Trying to install heroku-container-registry errors out with Error: Cannot find module 'inflection'

```shell
nchen@nchen-wsm1:~/Development|⇒  heroku --version
heroku-toolbelt/3.43.13 (x86_64-darwin10.8.0) ruby/1.9.3
heroku-cli/5.5.0-f6e6aaf (darwin-amd64) go1.7.3
```

```shell
nchen@nchen-wsm1:~/Development|⇒  heroku plugins:install heroku-container-registry
Installing plugin heroku-container-registry...module.js:442
    throw err;
    ^

Error: Cannot find module 'inflection'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/nchen/.local/share/heroku/plugins/node_modules/heroku-client/lib/resourceBuilder.js:4:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
 !
 ▸    Error installing plugin heroku-container-registry
 !    error installing plugin heroku-container-registry
```

**Comment by vazexqi** [comment]
Just had the chance to try this out again and it's working now for me. Might have been an intermittent issue on my end.

```shell
nchen@nchen-wsm1:~|⇒  heroku --version                                 11:47:06
heroku-cli/5.6.6-277bd36 (darwin-amd64) go1.7.4
nchen@nchen-wsm1:~|⇒  heroku plugins                                   11:47:13
heroku-container-registry 4.1.1
```
